name: Release Workflow

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for release tag
      run: |
        if [[ "${{ github.ref }}" != refs/tags/* ]]; then
          echo "This is not a release tag. Exiting..."
          exit 1
        fi
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}
        path: |
          data
          graphics
          jars
          mod_pictures
          sounds
          src
          consolegalaxy.version
          mod_info.json
          icon.png
          !.git
          !.github
          !.gradle
          !.idea
          !.run
          !build
          !libs
          !readme_resources
          !out
    - name: list files tag:1
      run: |
        cd ..
        ls -R
  uploadzip:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}
        path: artifact
    - name: Create zip
      run: |
        cd artifact
        zip -r ConsoleGalaxy-${{ github.ref_name }}.zip *
    - name: Upload zip
      uses: actions/upload-artifact@v2
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}-zip
        path: artifact/ConsoleGalaxy-${{ github.ref_name }}.zip
    - name: list files tag:2
      run: ls -R



