name: Release Workflow

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
# check if the push is a release tag
  check-tags:
    runs-on: ubuntu-latest

    steps:
    - name: Check for release tag
      run: |
        if [[ "${{ github.ref }}" != refs/tags/* ]]; then
          echo "This is not a release tag. Exiting..."
          exit 1
        fi

# start the release jobs
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: check-tags
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

  # upload the release artifact to memory, this is whats seen on the actions summary page under Artifacts
    - name: Upload artifact
      id: upload-artifact-id
      uses: actions/upload-artifact@v4
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}
        path: |
          data
          graphics
          jars
          mod_pictures
          sounds
          src
          consolegalaxy.version
          mod_info.json
          icon.png
          !.git
          !.github
          !.gradle
          !.idea
          !.run
          !build
          !libs
          !readme_resources
          !out

  # make a directory to download the artifact to
    - name: make directory
      run: |
        mkdir AA_zipped_Folder
        mkdir "Console Galaxy"

  # download the artifact to the directory
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}
        path: "Console Galaxy"

    - name: list files tag:1
      run: ls -R

  # zip the artifact with name "ConsoleGalaxy-${{ github.ref_name }}.zip"
    - name: zip artifact
      run: zip -r ./AA_zipped_Folder/ConsoleGalaxy.zip "Console Galaxy"

    - name: list files tag:2
      run: |
        ls -R
        ls -R AA_zipped_Folder
        ls -R "Console Galaxy"
        ls -R ${{ github.workspace }}

  # make a CHANGELOGS.md file
    - name: Update CHANGELOG
      id: changelog
      uses: requarks/changelog-action@v1
      with:
        token: ${{ github.token }}
        # tag: ${{ github.ref_name }}
        fromTag: ${{ github.ref_name }}
        toTag: v1.0.0a
        writeToFile: true
        changelogFilePath: CHANGELOGS.md
        excludeTypes: ''
        includeInvalidCommits: true
        reverseOrder: true
    
    - name: echo changelog
      run: |
        echo ${{ steps.changelog.outputs.changes }}


  # create a release with the CHANGELOGS.md file
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOGS.md
        generate_release_notes: true
        append_body: true
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}
        make_latest: true
        files: |
          AA_zipped_Folder/ConsoleGalaxy.zip
          CHANGELOGS.md
    
    - name: list files tag:4
      run: ls -R

  # # update the changelog file in the repository, please make a pull request locally after this
  #   - name: Update resources
  #     uses: test-room-7/action-update-file@v1
  #     with:
  #         file-path: CHANGELOGS.md
  #         commit-msg: Update resources
  #         github-token: ${{ secrets.GITHUB_TOKEN }}