name: Release Workflow

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - name: Check for release tag
    #   run: |
    #     if [[ "${{ github.ref }}" != refs/tags/* ]]; then
    #       echo "This is not a release tag. Exiting..."
    #       exit 1
    #     fi
    - name: Checkout code
      uses: actions/checkout@v4
    - run: mkdir ConsoleGalaxy_zipFolder
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}
        path: |
          data
          graphics
          jars
          mod_pictures
          sounds
          src
          consolegalaxy.version
          mod_info.json
          icon.png
          !.git
          !.github
          !.gradle
          !.idea
          !.run
          !build
          !libs
          !readme_resources
          !out
    - name: list files tag:1
      run: |
        cd ..
        ls -R
    
# download extract artifact into ConsoleGalaxy_zipFolder
  prepare-zip:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # with:
      #   clean: false    # without this checkout deletes empty folders after each use
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}
        path: ConsoleGalaxy_zipFolder
    - name: list files tag:2
      run: |
        cd ${{ github.workspace }}
        ls -R
    # create a zip file with name ConsoleGalaxy-${{ github.ref_name }}.zip
    - name: Create zip file
      run: |
        cd ConsoleGalaxy_zipFolder
        zip -r ConsoleGalaxy-${{ github.ref_name }}.zip .
    - name: list files tag:3
      run: ls -R
    # make a CHANGELOGS.md file
    - name: Create CHANGELOGS file
      run: |
        echo "Changes for version ${{ github.ref_name }}" > CHANGELOGS.md
        echo "==============================" >> CHANGELOGS.md
        git log --format=%B -n 10 $(git log -1 --pretty=format:"%h") >> CHANGELOGS.md
    # echo the CHANGELOGS file
    - name: Show CHANGELOGS
      run: cat CHANGELOGS.md
  