name: Release Workflow

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
# check if the push is a release tag
  check-tags:
    runs-on: ubuntu-latest

    steps:
    - name: Check for release tag
      run: |
        if [[ "${{ github.ref }}" != refs/tags/* ]]; then
          echo "This is not a release tag. Exiting..."
          exit 1
        fi

# start the release jobs
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: check-tags
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

  # upload the release artifact to memory, this is whats seen on the actions summary page under Artifacts
    - name: Upload artifact
      id: upload-artifact-id
      uses: actions/upload-artifact@v4
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}
        path: |
          data
          graphics
          jars
          mod_pictures
          sounds
          src
          consolegalaxy.version
          mod_info.json
          icon.png
          !.git
          !.github
          !.gradle
          !.idea
          !.run
          !build
          !libs
          !readme_resources
          !out

  # make a directory to download the artifact to
    - name: make directory
      run: |
        mkdir AA_zipped_Folder
        mkdir "Console Galaxy"

  # download the artifact to the directory
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}
        path: "Console Galaxy"

    - name: list files tag:1
      run: ls -R

  # zip the artifact with name "ConsoleGalaxy-${{ github.ref_name }}.zip"
    - name: zip artifact
      run: zip -r ./AA_zipped_Folder/ConsoleGalaxy.zip "Console Galaxy"

    - name: list files tag:2
      run: |
        ls -R
        ls -R AA_zipped_Folder
        ls -R "Console Galaxy"
        ls -R ${{ github.workspace }}

  # get previous tag
    - name: Get previous tag
      id: previoustag-id
      run: echo "::set-output name=tag-previous::$(git describe --tags --abbrev=0 HEAD~1)"

    - name: Show previous tag
      run: echo ${{ steps.previoustag-id.outputs.tag-previous }}

    - name: git log between previous and current tag
      run: git log ${{ steps.previoustag-id.outputs.tag-previous }}..${{ github.ref }}

# we are creating two separate changelog files, one for the repository and one for the release page:
  
  # make main CHANGELOGS.md file for the repository
  # CHANGELOGS.md <--- this changelog is the main changelog file that will be updated on the repository, it contains last 10 commits
    - name: Create CHANGELOGS file
      run: |
        echo ${{ github.ref_name }} >> CHANGELOGS.md
        echo "Changes for version ${{ github.ref_name }}" >> CHANGELOGS.md
        echo "===========================" >> CHANGELOGS.md
        git log -10 --pretty="format:Title: %s%n%nCommits:%n\`\`\`%n%b\`\`\`%n>By: %cn%n>Hash: %h%n>Date: %ci %n%n----------------------------------------------%n" >> CHANGELOGS.md
    
  # make a CHANGELOGS.md file for the release and mod manager
  # AA_zipped_Folder/CHANGELOGS.md <--- this changelog is the changelog file that will be released on the release page, it only contains the changes of the current release, (HEAD^..HEAD) means between previous and current commit. 
    - name: Create CHANGELOGS file
      run: |
        echo ${{ github.ref_name }} >> CHANGELOGS.md
        echo "Changes for version ${{ github.ref_name }}" >> CHANGELOGS.md
        echo "===========================" >> CHANGELOGS.md
        git log ${{ steps.previoustag-id.outputs.tag-previous }}..${{ github.ref }} --pretty="format:Title: %s%n%nCommits:%n\`\`\`%n%b\`\`\`%n>By: %cn%n>Hash: %h%n>Date: %ci %n%n----------------------------------------------%n" >> AA_zipped_Folder/CHANGELOGS.md

    - name: Show CHANGELOGS
      run: cat CHANGELOGS.md
    - name: list files tag:3
      run: ls -R

    # echo the changelog to the output
    - name: Get changelog
      id: changelog
      run: echo "::set-output name=changelog::$(cat CHANGELOGS.md)"


  # create a release with the CHANGELOGS.md file
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOGS.md
        generate_release_notes: true
        append_body: true
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}
        make_latest: true
        files: |
          AA_zipped_Folder/ConsoleGalaxy.zip
          AA_zipped_Folder/CHANGELOGS.md
    
    - name: list files tag:4
      run: ls -R

  # # update the changelog file in the repository, please make a pull request locally after this
  #   - name: Update resources
  #     uses: test-room-7/action-update-file@v1
  #     with:
  #         file-path: CHANGELOGS.md
  #         commit-msg: Update resources
  #         github-token: ${{ secrets.GITHUB_TOKEN }}