name: Release Workflow

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for release tag
      run: |
        if [[ "${{ github.ref }}" != refs/tags/* ]]; then
          echo "This is not a release tag. Exiting..."
          exit 1
        fi
    - run: mkdir ConsoleGalaxy_zipFolder
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}
        path: |
          data
          graphics
          jars
          mod_pictures
          sounds
          src
          consolegalaxy.version
          mod_info.json
          icon.png
          !.git
          !.github
          !.gradle
          !.idea
          !.run
          !build
          !libs
          !readme_resources
          !out
    - name: list files tag:1
      run: |
        cd ..
        ls -R
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: ConsoleGalaxy-${{ github.ref_name }}
        draft: false
        prerelease: false
        #body_path: CHANGELOG.md
    
    - name: Realease to Github Releases
      uses: ncipollo/release-action@v1
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}             # Release post Title Name
        artifacts: ConsoleGalaxy-${{ github.ref_name }}.zip         # Release File name
        token: ${{ secrets.GITHUB_TOKEN }}
        #generateReleaseNotes: true
      
