name: Release Workflow

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - name: Check for release tag
    #   run: |
    #     if [[ "${{ github.ref }}" != refs/tags/* ]]; then
    #       echo "This is not a release tag. Exiting..."
    #       exit 1
    #     fi
    - name: Checkout code
      uses: actions/checkout@v4
    - run: mkdir ConsoleGalaxy_zipFolder
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}
        path: |
          data
          graphics
          jars
          mod_pictures
          sounds
          src
          consolegalaxy.version
          mod_info.json
          icon.png
          !.git
          !.github
          !.gradle
          !.idea
          !.run
          !build
          !libs
          !readme_resources
          !out
    - name: list files tag:1
      run: |
        cd ..
        ls -R
    
# download extract artifact into ConsoleGalaxy_zipFolder
  prepare-zip:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # with:
      #   clean: false    # without this checkout deletes empty folders after each use
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}
        path: ConsoleGalaxy_zipFolder
    - name: list files tag:2
      run: |
        cd ${{ github.workspace }}
        ls -R
    # create a zip file with name ConsoleGalaxy-${{ github.ref_name }}.zip
    - name: Create zip file
      id: make-zip-id
      run: |
        cd ConsoleGalaxy_zipFolder
        zip -r ConsoleGalaxy-${{ github.ref_name }}.zip .
    - name: list files tag:3
      run: ls -R
# make a CHANGELOGS.md file
    - name: Create CHANGELOGS file
      id: CHANGELOGS-file-id
      run: |
        echo "Changes for version ${{ github.ref_name }}" > CHANGELOGS.md
        echo "==============================" >> CHANGELOGS.md
        git log -10 --pretty="format:Title: %s%n%nCommits:%n%b%nBy: %cn%nHash: %h%nDate: %aD (%cr)%n----------------------------------%n" >> CHANGELOGS.md
    # echo the CHANGELOGS file
    - name: Show CHANGELOGS
      run: cat CHANGELOGS.md
    - name: list files tag:4
      run: ls -R
    outputs:
      output1: ${{ steps.make-zip-id.outputs.zip-file }}
      output2: ${{ steps.CHANGELOGS-file-id.outputs.CHANGELOGS.md }}

  release:
    runs-on: ubuntu-latest
    needs: prepare-zip
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create a release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ${{ needs.prepare-zip.outputs.output2 }}
        draft: false
        prerelease: false
    - name: list files tag:5
      run: ls -R
    - name: Upload release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.prepare-zip.outputs.upload_url }}
        asset_path: ConsoleGalaxy_zipFolder/ConsoleGalaxy-${{ github.ref_name }}.zip
        asset_name: ConsoleGalaxy-${{ github.ref_name }}.zip
        asset_content_type: application/zip
    - name: list files tag:6
      run: ls -R
