name: Release Workflow

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for release tag
      run: |
        if [[ "${{ github.ref }}" != refs/tags/* ]]; then
          echo "This is not a release tag. Exiting..."
          exit 1
        fi
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}
        path: |
          data
          graphics
          jars
          mod_pictures
          sounds
          src
          consolegalaxy.version
          mod_info.json
          icon.png
    - name: list files tag:1
      run: ls -l
  update_release_draft:
    needs: build
    permissions:
        # write permission is required to create a github release
        contents: write
        # write permission is required for autolabeler
        # otherwise, read permission is required at least
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Drafts the next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


