name: Release Workflow

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for release tag
      run: |
        if [[ "${{ github.ref }}" != refs/tags/* ]]; then
          echo "This is not a release tag. Exiting..."
          exit 1
        fi

    - name: Generate changelog
      run: |
        gem install github_changelog_generator
        github_changelog_generator -u ${{ github.repository_owner }} -p ${{ github.event.repository.name }} --token ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}
        path: |
          data
          graphics
          jars
          mod_pictures
          sounds
          src
          consolegalaxy.version
          mod_info.json
          icon.png
          CHANGELOG.md
    - name: check download-artifact file log
      run: ls -R

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: ConsoleGalaxy-${{ github.ref_name }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ConsoleGalaxy-${{ github.ref_name }}.zip
        asset_name: ConsoleGalaxy-${{ github.ref_name }}.zip
        asset_content_type: application/zip